language: csharp
solution: "./PlayingCards/PlayingCards.sln"
script:
    - mono ../lib/xunit/xunit.console.clr4.x86.exe ./PlayingCards/TestPlayingCards_xUnit/bin/Debug/TestPlayingCards_xUnit.dll
    
    
    